namespace ReactNativeLauncherWindows
{
  [webhosthidden]
  [default_interface]
  runtimeclass ReactPackageProvider : Microsoft.ReactNative.IReactPackageProvider
  {
    ReactPackageProvider();
  };
}
